### ISSUE TITLE
Unclear effect of keyword arguments in Polyco.phasepol() method 

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband-tasks#131]
There's unexplained behavior for the Polyco.phasepol() method.

There is a keyword "convert" which can either be True or False. It is False by default, however the module docstring recommends:

    For use with folding codes with times since some start time t0 in seconds:
    >>> psr_polyco.phasepol(t0, 'fraction', t0=t0, time_unit=u.second, convert=True)

with no explanation for why the `convert=True` is necessary. Testing on my part shows that there is no measurable effect of this keyword as far as our use case is concerned. Why is the default value different than the implied "recommended" usage in the main docstring? Why is the keyword available at all if it doesn't affect the use case we are interested in?

Then, there are the arguments `t0` and `time_unit` which are also undocumented. How `t0` works and how to use it correctly would be useful, since the usage example simply sets it to the same value as the primary argument which isn't very instructive.

**Comment by mhvk** [comment]
the main benefit of `convert` is that the polynomial coefficients are actually those at the start of the observation (i.e., f, fdot) and are thus somewhat easier to interpret. With `convert=False`, the coefficients are at some reference time and the conversion is done by mapping (through window/domain). I think it indeed should have no significant effect on precision...

Since polynomials have no time units, one can choose that here (by default, tempo1 uses minutes, which is perhaps unexpected). 

Anyway, I really should just update the docstring, and will take this issue as a reminder for that!

**Comment by theXYZT** [comment]
Why not set convert=True by default and eliminate it as a keyword argument from Polyco.phasepol()? This doesn't restrict functionality because the user always has access to Polyco.polynomial().

Since all Polyco.phasepol() does is call Polyco.polynomial() with a restricted set of arguments, I see nothing wrong with restricting it a bit further for the relevant use case.
