### ISSUE TITLE
Does PaddedTask pad zeros in the beginning and end?

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband-tasks#231]
https://github.com/mhvk/baseband-tasks/blob/ded2b6f0d28afab16cc9d407e4f57823456df6e5/baseband_tasks/base.py#L741

I always thought the padded class also adds zeros at the beginning and the end of data stream. It seems not true just looking at the code.

**Comment by mhvk** [comment]
The padded class assumes you need real data even where padded (e.g., for dedisperson) so it does not add zeros, since those would enter the output stream. I think for our `SampleShift`, this is OK - no need to worry about the beginning and start too much! Though I guess we will eventually need a separate class that fills in samples with zeros so that we can read back the gated data and that might as well allow one to extend the data.

**Comment by luojing1211** [comment]
How does the padding work on the edge of a frame. If my offset is at the beginning of a frame, will the underlying offset be in the previous frame? I have some tests on the frame edges and it failing right now. #226

**Comment by mhvk** [comment]
I think #226 was a red herring, and the padded task base thankfully works as expected. So, will close. Do re-open if there is a problem after all!
